// This file is auto-generated by @hey-api/openapi-ts

export type RoleDto = {
    id?: number;
    name?: string;
};

export type UserDto = {
    id?: number;
    username?: string;
    email?: string;
    roles?: Array<RoleDto>;
};

export type UserWatchlistMovieDto = {
    movieId: number;
};

export type UserFavoriteMovieDto = {
    movieId: number;
};

export type CategoryDto = {
    id?: number;
    name?: string;
};

export type DirectorDto = {
    id?: number;
    name?: string;
};

export type MovieDto = {
    id?: number;
    title?: string;
    description?: string;
    director?: DirectorDto;
    categories?: Array<CategoryDto>;
    releaseDate?: string;
    language?: string;
    country?: string;
    posterUrl?: string;
    metacriticRating?: number;
    imdbRating?: number;
    runtime?: number;
};

export type FetchTitlesResponseDto = {
    titles?: Array<MovieDto>;
};

export type UserCommentDto = {
    parentCommentId?: number;
    content: string;
};

export type CommentDto = {
    id?: number;
    user?: UserDto;
    children?: Array<CommentDto>;
    content?: string;
    createdAt?: string;
};

export type RegisterRequestDto = {
    username: string;
    email: string;
    password: string;
};

export type RegisterResponseDto = {
    userDTO?: UserDto;
};

export type LoginRequestDto = {
    username?: string;
    password?: string;
};

export type LoginResponseDto = {
    token?: string;
};

export type UserMovieWatchlistResponseDto = {
    user?: UserDto;
    watchlist?: Array<MovieDto>;
};

export type UserMovieFavoriteResponseDto = {
    user?: UserDto;
    favorites?: Array<MovieDto>;
};

export type Pageable = {
    page?: number;
    size?: number;
    sort?: Array<string>;
};

export type UserUnwatchlistMovieDto = {
    movieId: number;
};

export type UserUnfavoriteMovieDto = {
    movieId: number;
};

export type UserDeleteCommentDto = {
    commentId: number;
};

export type DeleteUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type DeleteUserResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUserByIdResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type UpdateUserData = {
    body: UserDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type RemoveFromWatchlistData = {
    body: UserUnwatchlistMovieDto;
    path?: never;
    query?: never;
    url: '/users/movie/watchlist';
};

export type RemoveFromWatchlistResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type AddToWatchlistData = {
    body: UserWatchlistMovieDto;
    path?: never;
    query?: never;
    url: '/users/movie/watchlist';
};

export type AddToWatchlistResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UnfavoriteMovieData = {
    body: UserUnfavoriteMovieDto;
    path?: never;
    query?: never;
    url: '/users/movie/favorite';
};

export type UnfavoriteMovieResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type FavoriteMovieData = {
    body: UserFavoriteMovieDto;
    path?: never;
    query?: never;
    url: '/users/movie/favorite';
};

export type FavoriteMovieResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteMovieData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/movies/{id}';
};

export type DeleteMovieResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetMovieByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/movies/{id}';
};

export type GetMovieByIdResponses = {
    /**
     * OK
     */
    200: MovieDto;
};

export type GetMovieByIdResponse = GetMovieByIdResponses[keyof GetMovieByIdResponses];

export type UpdateMovieData = {
    body: MovieDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/movies/{id}';
};

export type UpdateMovieResponses = {
    /**
     * OK
     */
    200: MovieDto;
};

export type UpdateMovieResponse = UpdateMovieResponses[keyof UpdateMovieResponses];

export type DeleteDirectorData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/directors/{id}';
};

export type DeleteDirectorResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetDirectorByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/directors/{id}';
};

export type GetDirectorByIdResponses = {
    /**
     * OK
     */
    200: DirectorDto;
};

export type GetDirectorByIdResponse = GetDirectorByIdResponses[keyof GetDirectorByIdResponses];

export type UpdateDirectorData = {
    body: DirectorDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/directors/{id}';
};

export type UpdateDirectorResponses = {
    /**
     * OK
     */
    200: DirectorDto;
};

export type UpdateDirectorResponse = UpdateDirectorResponses[keyof UpdateDirectorResponses];

export type DeleteCategoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/categories/{id}';
};

export type DeleteCategoryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCategoryByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/categories/{id}';
};

export type GetCategoryByIdResponses = {
    /**
     * OK
     */
    200: CategoryDto;
};

export type GetCategoryByIdResponse = GetCategoryByIdResponses[keyof GetCategoryByIdResponses];

export type UpdateCategoryData = {
    body: CategoryDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/categories/{id}';
};

export type UpdateCategoryResponses = {
    /**
     * OK
     */
    200: CategoryDto;
};

export type UpdateCategoryResponse = UpdateCategoryResponses[keyof UpdateCategoryResponses];

export type GetAllMoviesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/movies';
};

export type GetAllMoviesResponses = {
    /**
     * OK
     */
    200: Array<MovieDto>;
};

export type GetAllMoviesResponse = GetAllMoviesResponses[keyof GetAllMoviesResponses];

export type CreateMovieData = {
    body: MovieDto;
    path?: never;
    query?: never;
    url: '/movies';
};

export type CreateMovieResponses = {
    /**
     * OK
     */
    200: MovieDto;
};

export type CreateMovieResponse = CreateMovieResponses[keyof CreateMovieResponses];

export type FetchAndSaveTitlesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/imdb/fetch-titles';
};

export type FetchAndSaveTitlesResponses = {
    /**
     * OK
     */
    200: FetchTitlesResponseDto;
};

export type FetchAndSaveTitlesResponse = FetchAndSaveTitlesResponses[keyof FetchAndSaveTitlesResponses];

export type GetAllDirectorsData = {
    body?: never;
    path?: never;
    query: {
        pageable: Pageable;
    };
    url: '/directors';
};

export type GetAllDirectorsResponses = {
    /**
     * OK
     */
    200: Array<DirectorDto>;
};

export type GetAllDirectorsResponse = GetAllDirectorsResponses[keyof GetAllDirectorsResponses];

export type CreateDirectorData = {
    body: DirectorDto;
    path?: never;
    query?: never;
    url: '/directors';
};

export type CreateDirectorResponses = {
    /**
     * OK
     */
    200: DirectorDto;
};

export type CreateDirectorResponse = CreateDirectorResponses[keyof CreateDirectorResponses];

export type GetCommentsByMovieData = {
    body?: never;
    path: {
        movieId: number;
    };
    query?: never;
    url: '/comments/movie/{movieId}';
};

export type GetCommentsByMovieResponses = {
    /**
     * OK
     */
    200: Array<CommentDto>;
};

export type GetCommentsByMovieResponse = GetCommentsByMovieResponses[keyof GetCommentsByMovieResponses];

export type AddCommentData = {
    body: UserCommentDto;
    path: {
        movieId: number;
    };
    query?: never;
    url: '/comments/movie/{movieId}';
};

export type AddCommentResponses = {
    /**
     * OK
     */
    200: CommentDto;
};

export type AddCommentResponse = AddCommentResponses[keyof AddCommentResponses];

export type GetAllCategoriesData = {
    body?: never;
    path?: never;
    query: {
        pageable: Pageable;
    };
    url: '/categories';
};

export type GetAllCategoriesResponses = {
    /**
     * OK
     */
    200: Array<CategoryDto>;
};

export type GetAllCategoriesResponse = GetAllCategoriesResponses[keyof GetAllCategoriesResponses];

export type CreateCategoryData = {
    body: CategoryDto;
    path?: never;
    query?: never;
    url: '/categories';
};

export type CreateCategoryResponses = {
    /**
     * OK
     */
    200: CategoryDto;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type RegisterData = {
    body: RegisterRequestDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: RegisterResponseDto;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: LoginRequestDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: LoginResponseDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetUserByUsernameData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/users/username/{username}';
};

export type GetUserByUsernameResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetUserByUsernameResponse = GetUserByUsernameResponses[keyof GetUserByUsernameResponses];

export type GetUserWatchlistData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/users/username/{username}/watchlist';
};

export type GetUserWatchlistResponses = {
    /**
     * OK
     */
    200: UserMovieWatchlistResponseDto;
};

export type GetUserWatchlistResponse = GetUserWatchlistResponses[keyof GetUserWatchlistResponses];

export type GetUserFavoritesData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/users/username/{username}/favorites';
};

export type GetUserFavoritesResponses = {
    /**
     * OK
     */
    200: UserMovieFavoriteResponseDto;
};

export type GetUserFavoritesResponse = GetUserFavoritesResponses[keyof GetUserFavoritesResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetMeResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type GetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/';
};

export type GetAllUsersResponses = {
    /**
     * OK
     */
    200: Array<UserDto>;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type GetAllRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/roles';
};

export type GetAllRolesResponses = {
    /**
     * OK
     */
    200: Array<RoleDto>;
};

export type GetAllRolesResponse = GetAllRolesResponses[keyof GetAllRolesResponses];

export type SearchMoviesData = {
    body?: never;
    path?: never;
    query: {
        query: string;
    };
    url: '/movies/search';
};

export type SearchMoviesResponses = {
    /**
     * OK
     */
    200: Array<MovieDto>;
};

export type SearchMoviesResponse = SearchMoviesResponses[keyof SearchMoviesResponses];

export type DeleteCommentData = {
    body: UserDeleteCommentDto;
    path?: never;
    query?: never;
    url: '/comments/';
};

export type DeleteCommentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8080' | (string & {});
};